---
- name: Setup jenkins automation server
  hosts: admin
  become: true
  gather_facts: false
  roles:
    - jenkins-setup

- name: Setup docker platform
  hosts: admin
  become: true
  gather_facts: false
  roles:
    - docker-setup

- name: Setup kubectl command
  hosts: admin
  become: true
  gather_facts: false
  roles:
    - kubectl-setup
